### ISSUE TITLE
how to keep white_bg?

### ISSUE THREAD

**Issue by zAuk000** [abhayran/styleNeRF#7]
Hi, I think it is an inspiring work about NeRF editing, and I want to know how to keep the white background when running style transfer, sry that I can't find the key code or process , hope that you can give me some advice, thanks!

**Comment by abhayran** [comment]
`--stage style` flag should freeze the density network, which allows to keep the background white.

**Comment by zAuk000** [comment]
> `--stage style` flag should freeze the density network, which allows to keep the background white.

Thank you, but I would like to know why we can do this. We only freeze the geometric layers, but why doesn't the color of the style image cover the white background during style transfer? Does this have to do with the number of iterations? If we continue training for style transfer, will the white background also be covered by the colors of the style image?

**Comment by abhayran** [comment]
> > `--stage style` flag should freeze the density network, which allows to keep the background white.
> 
> Thank you, but I would like to know why we can do this. We only freeze the geometric layers, but why doesn't the color of the style image cover the white background during style transfer? Does this have to do with the number of iterations? If we continue training for style transfer, will the white background also be covered by the colors of the style image?

No, freezing the density network means that background will always stay white. If you don't do that, you will get the whole scene filled up, which we didn't want to be the case. But if for some reason you want that, just comment out the line 326 in `pipeline.py`:
`pl.set_requires_grad(requires_grad=False)  # freeze density layer`

**Comment by zAuk000** [comment]
> > > `--stage style` flag should freeze the density network, which allows to keep the background white.
> > 
> > 
> > Thank you, but I would like to know why we can do this. We only freeze the geometric layers, but why doesn't the color of the style image cover the white background during style transfer? Does this have to do with the number of iterations? If we continue training for style transfer, will the white background also be covered by the colors of the style image?
> 
> No, freezing the density network means that background will always stay white. If you don't do that, you will get the whole scene filled up, which we didn't want to be the case. But if for some reason you want that, just comment out the line 326 in `pipeline.py`: `pl.set_requires_grad(requires_grad=False) # freeze density layer`

okay, I'm sorry for misunderstanding some of the meanings about the white background. Now I understand, thank you for explaining.
